"""Sentencias SQL literales del paquete CROSS 0101 SSIS_CL_Senalizaciones.dtsx.

Se conservan exactamente como estaban en los Execute SQL Task originales
(los separadores 'GO' de SSIS/SSMS se eliminan y cada sentencia se ejecuta
por separado, ya que 'GO' no es SQL valido para un driver OLE DB/ODBC).
"""

TRUNCATE_FUNNEL_SENALIZACIONES = (
    "TRUNCATE TABLE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES]"
)

EXEC_SP_FUNNEL_SENHALIZACIONES = "EXEC [CL_USUARIOS].[dbo].[SP_FUNNEL_SENHALIZACIONES]"

# Task "UPDATE" (outer): 18 correcciones literales de TU DNI.
# Se conserva la fila duplicada ('004981615' / '4981615') tal como esta en el
# .dtsx original (es inocua: un UPDATE sobre un WHERE que ya no matchea nada).
DNI_LITERAL_FIXUPS: tuple[str, ...] = (
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '002577992' WHERE [TU DNI] = '2577992'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '003323113' WHERE [TU DNI] = '3323113'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '003328048' WHERE [TU DNI] = '3328048'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '003343872' WHERE [TU DNI] = '3343872'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '003460521' WHERE [TU DNI] = '3460521'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '003686853' WHERE [TU DNI] = '3686853'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '003814303' WHERE [TU DNI] = '3814303'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '004111606' WHERE [TU DNI] = '4111606'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '004981615' WHERE [TU DNI] = '4981615'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '004981615' WHERE [TU DNI] = '4981615'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '005832728' WHERE [TU DNI] = '5832728'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '06034261' WHERE [TU DNI] = '6034261'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '07215509' WHERE [TU DNI] = '7215509'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '007519207' WHERE [TU DNI] = '7519207'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '07528394' WHERE [TU DNI] = '7528394'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '08817881' WHERE [TU DNI] = '8817881'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '09344499' WHERE [TU DNI] = '9344499'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '09399377' WHERE [TU DNI] = '9399377'",
    "UPDATE [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] "
    "SET [TU DNI] = '09488600' WHERE [TU DNI] = '9488600'",
)

# Task "UPDATE" (inner, dentro de "Contenedor de secuencias"): corrige TU DNI
# usando el catalogo TBL_FUNNEL_SENHALIZACIONES_DNI.
UPDATE_DNI_FROM_CATALOG = """
WITH nuevo_dni as
(
SELECT [DNI ORIGEN]
      ,[DNI A CAMBIAR]
      ,[Observación]
  FROM [CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES_DNI]
  WHERE [DNI A CAMBIAR] IS NOT NULL
)

UPDATE x0
SET
	[TU DNI] = x1.[DNI A CAMBIAR]
FROM
	[CL_USUARIOS].[dbo].[TBL_FUNNEL_SENHALIZACIONES] x0
INNER JOIN
	nuevo_dni x1
ON
	x1.[DNI ORIGEN] = x0.[TU DNI]
"""
