-- Tarea 'SECUENCIA NUEVA\Contenedor de secuencias 1\INSERT', conexión 162.CL_ISN.
INSERT INTO [CL_ISN].[dbo].[TBL_ISN_PRE_CONSOLIDADO]
(
[FECHA_EVENTO]
      ,[HORA_EVENTO]
      ,[ANI_EVENTO]
      ,[ANI_CONTACTO]
      ,[ID_PROVEEDOR]
      ,[ENCUESTA]
      ,[NEGOCIO]
      ,[PROCESO_NIVEL1]
      ,[PROCESO_NIVEL2]
      ,[PROCESO_NIVEL3]
      ,[PROCESO_NIVEL4]
      ,[PROCESO_NIVEL5]
      ,[EMPRESA]
      ,[ZONA]
      ,[REGION]
      ,[COMUNA]
      ,[AGENCIA]
      ,[SUBSEGMENTO]
      ,[TIPO_CONTRATO]
      ,[PRODUCTO]
      ,[TECNOLOGIA]
      ,[RUT_CLIENTE]
      ,[NOMBRE_CLIENTE]
      ,[RUT_EJECUTIVO]
      ,[NOMBRE_EJECUTIVO]
      ,[RUT_TECNICO]
      ,[NOMBRE_TECNICO]
      ,[PCRC]
      ,[BASE]
      ,[Número del caso]
      ,[REFERIDO]
      ,[Indice]
	  ,[FECHA_DE_CARGA]
)

SELECT [FECHA_EVENTO]
      ,[HORA_EVENTO]
      ,[ANI_EVENTO]
      ,[ANI_CONTACTO]
      ,[ID_PROVEEDOR]
      ,[ENCUESTA]
      ,[NEGOCIO]
      ,[PROCESO_NIVEL1]
      ,[PROCESO_NIVEL2]
      ,[PROCESO_NIVEL3]
      ,[PROCESO_NIVEL4]
      ,[PROCESO_NIVEL5]
      ,[EMPRESA]
      ,[ZONA]
      ,[REGION]
      ,[COMUNA]
      ,[AGENCIA]
      ,[SUBSEGMENTO]
      ,[TIPO_CONTRATO]
      ,[PRODUCTO]
      ,[TECNOLOGIA]
      ,[RUT_CLIENTE]
      ,[NOMBRE_CLIENTE]
      ,[RUT_EJECUTIVO]
      ,[NOMBRE_EJECUTIVO]
      ,[RUT_TECNICO]
      ,[NOMBRE_TECNICO]
      ,[PCRC]
      ,[BASE]
      ,[Número del caso]
      ,[REFERIDO]
      ,[Indice]
	  ,CAST(GETDATE() AS date) [FECHA_DE_CARGA]
  FROM [CL_ISN].[dbo].[TBL_ISN_PRE]
