-- Origen SSIS: Execute SQL Task "TBLS AUXILIARES"
-- Conexion original: 162.CL_ISN
-- Contiene 4 bloques separados por GO (batches). El runner de Python
-- (database/connection.py:execute_script) los ejecuta uno a uno.

--TBL_TERMOMETRO_<8

IF EXISTS
	(
		SELECT *
		FROM CL_ISN.INFORMATION_SCHEMA.TABLES
		WHERE
				TABLE_NAME='TBL_TERMOMETRO_<8'
			AND TABLE_SCHEMA='DBO'
	)
BEGIN
	DROP TABLE [CL_ISN].[dbo].[TBL_TERMOMETRO_<8]
END
GO

DECLARE @var1 VARCHAR(30)

SELECT
	@var1= MAX(periodo)
FROM
	[CL_CAMPAÑAS].[dbo].[TBL_CAMPAÑA_TERMOMETRO]

SELECT
	RUT_SIN_DV [RUT]
	,'TERMOMETRO' [BASE]
INTO
	[CL_ISN].[dbo].[TBL_TERMOMETRO_<8]
FROM
	[CL_CAMPAÑAS].[dbo].[TBL_CAMPAÑA_TERMOMETRO]
WHERE
	periodo = @var1
	and [Prom 14.] <9
GROUP BY
	RUT_SIN_DV
GO

--TBL_CCAA_DISTINTOS_NUMERO_CLIENTE
IF EXISTS
	(
		SELECT *
		FROM CL_ISN.INFORMATION_SCHEMA.TABLES
		WHERE
				TABLE_NAME='TBL_CCAA_DISTINTOS_NUMERO_CLIENTE'
			AND TABLE_SCHEMA='DBO'
	)
BEGIN
	DROP TABLE [CL_ISN].[dbo].[TBL_CCAA_DISTINTOS_NUMERO_CLIENTE]
END
GO

SELECT [Número]
      ,[RUT]
INTO [CL_ISN].[dbo].[TBL_CCAA_DISTINTOS_NUMERO_CLIENTE]
FROM [CL_ANALISIS].[dbo].[VIEW_SF_CCAA_DISTINTOS_NUMERO_CLIENTE]
GO

--TBL_CCAA_RUT_CONTACTO_NUMERO
IF EXISTS
	(
		SELECT *
		FROM CL_ISN.INFORMATION_SCHEMA.TABLES
		WHERE
				TABLE_NAME='TBL_CCAA_RUT_CONTACTO_NUMERO'
			AND TABLE_SCHEMA='DBO'
	)
BEGIN
	DROP TABLE [CL_ISN].[dbo].[TBL_CCAA_RUT_CONTACTO_NUMERO]
END
GO

SELECT
	*
INTO [CL_ISN].[dbo].[TBL_CCAA_RUT_CONTACTO_NUMERO]
FROM [CL_ANALISIS].[dbo].[VIEW_SF_CCAA_RUT_CONTACTO_NUMERO]
GO

--TBL_CCAA_DISTINTOS_QCLENTES
IF EXISTS
	(
		SELECT *
		FROM CL_ISN.INFORMATION_SCHEMA.TABLES
		WHERE
				TABLE_NAME='TBL_CCAA_DISTINTOS_QCLENTES'
			AND TABLE_SCHEMA='DBO'
	)
BEGIN
	DROP TABLE [CL_ISN].[dbo].[TBL_CCAA_DISTINTOS_QCLENTES]
END
GO

SELECT
	*
INTO [CL_ISN].[dbo].[TBL_CCAA_DISTINTOS_QCLENTES]
FROM [CL_ANALISIS].[dbo].[VIEW_SF_CCAA_DISTINTOS_QCLENTES]
GO
