-- Origen SSIS: Execute SQL Task "DROP" (dentro de "TBL_ISN")
-- Conexion original: 162.CL_ISN
IF EXISTS
	(
		SELECT *
		FROM CL_ISN.INFORMATION_SCHEMA.TABLES
		WHERE
			TABLE_NAME='TBL_ISN'
		 AND TABLE_SCHEMA='DBO'
	)
BEGIN
	DROP TABLE [CL_ISN].[dbo].[TBL_ISN]
END
GO
