-- Origen SSIS: OLE DB Source "TBL_ISN" dentro del Data Flow Task "EXPORT CSV" (AccessMode=2, SQL Command)
-- Conexion original: 162.CL_ISN
-- Pass-through puro: estas 28 columnas se escriben sin transformacion al CSV (isn.csv)
SELECT
	[FECHA_EVENTO]
    ,[HORA_EVENTO]
    ,[ANI_EVENTO]
    ,[ANI_CONTACTO]
    ,[ID_PROVEEDOR]
    ,[ENCUESTA]
    ,[NEGOCIO]
    ,[PROCESO_NIVEL1]
    ,[PROCESO_NIVEL2]
    ,[PROCESO_NIVEL3]
    ,[PROCESO_NIVEL4]
    ,[PROCESO_NIVEL5]
    ,[EMPRESA]
    ,[ZONA]
    ,[REGION]
    ,[COMUNA]
    ,[AGENCIA]
    ,[SUBSEGMENTO]
    ,[TIPO_CONTRATO]
    ,[PRODUCTO]
    ,[TECNOLOGIA]
    ,[RUT_CLIENTE]
    ,[NOMBRE_CLIENTE]
    ,[RUT_EJECUTIVO]
    ,[NOMBRE_EJECUTIVO]
    ,[RUT_TECNICO]
    ,[NOMBRE_TECNICO]
    ,[PCRC]
FROM
	[CL_ISN].[dbo].[TBL_ISN]
