-- Origen SSIS: Execute SQL Task "UPDATE TBL_ISN_ENVIOS_CONSOLIDADOS" (dentro de "ACTUALIZACION SERVIDOR")
-- Conexion original: 162.CL_CALIDAD
UPDATE [CL_CALIDAD].[dbo].[TBL_ISN_ENVIOS_CONSOLIDADO]
SET [FECHA DE CARGA] = CAST(GETDATE() AS date)
WHERE [FECHA DE CARGA] IS NULL
