-- Tarea 'SECUENCIA NUEVA\Contenedor de secuencias\INSERT', conexión 162.CL_ISN.
INSERT INTO
[CL_ISN].[dbo].[TBL_ISN_SF_CONSOLIDADO]
	(
	[ORDEN]
	,[FECHA]
	,[HORA]
	,[COD_DNI SM CARTERA]
	,[RUT SM CARTERA]
	,[NOMBRE SM CARTERA]
	,[Fecha de cierre general]
	,[Fecha/Hora de apertura]
	,[Número del caso]
	,[Estado]
	,[Estado general]
	,[No. identificación fiscal]
	,[Vista final]
	,[Origen]
	,[Programa Responsable]
	,[Asesor Responsable DNI]
	,[Asesor responsable]
	,[Coordinador responsable]
	,[Correo Electrónico Contacto]
	,[Teléfono Contacto]
	,[Teléfono Móvil Contacto]
	,[Correo Electronico Web]
	,[Teléfono Móvil Correo electrónico web]
	,[Teléfono Fijo Correo electrónico web]
	,[ANI]
	,[SUB_SEGMENTO]
	,[NOMBRE_CLIENTE]
	,[SEGMENTO]
	,[RUT YA ENCUESTADO]
	,[DNI ASESOR<30 DIAS]
	,[OJT PLACE]
	,[CLIENTE CON PENDIENTE]
	,[CLIENTE CON RECLAMO]
	,[CLIENTE DETRACTOR CALIDAD]
	,[BASE]
	,[GRUPO DOMINIO]
	,[ESTADO PRESENTACION]
	,[MOTIVO DE RETIRO]
	,[FECHA_DE_CARGA]
	)

SELECT [ORDEN]
      ,[FECHA]
      ,[HORA]
      ,[COD_DNI SM CARTERA]
      ,[RUT SM CARTERA]
      ,[NOMBRE SM CARTERA]
      ,[Fecha de cierre general]
      ,[Fecha/Hora de apertura]
      ,[Número del caso]
      ,[Estado]
      ,[Estado general]
      ,[No. identificación fiscal]
      ,[Vista final]
      ,[Origen]
      ,[Programa Responsable]
      ,[Asesor Responsable DNI]
      ,[Asesor responsable]
      ,[Coordinador responsable]
      ,[Correo Electrónico Contacto]
      ,[Teléfono Contacto]
      ,[Teléfono Móvil Contacto]
      ,[Correo Electronico Web]
      ,[Teléfono Móvil Correo electrónico web]
      ,[Teléfono Fijo Correo electrónico web]
      ,[ANI]
      ,[SUB_SEGMENTO]
      ,[NOMBRE_CLIENTE]
      ,[SEGMENTO]
      ,[RUT YA ENCUESTADO]
      ,[DNI ASESOR<30 DIAS]
      ,[OJT PLACE]
      ,[CLIENTE CON PENDIENTE]
      ,[CLIENTE CON RECLAMO]
      ,[CLIENTE DETRACTOR CALIDAD]
      ,[BASE]
      ,[GRUPO DOMINIO]
      ,[ESTADO PRESENTACION]
      ,[MOTIVO DE RETIRO]
	  ,CAST(GETDATE() AS date) [FECHA_DE_CARGA]
  FROM [CL_ISN].[dbo].[TBL_ISN_SF]
