-- Tarea 'TBL_ISN_CALIDAD\ACTUALIZACION SERVIDOR\UPDATE TBL_ISN_ENVIOS_CONSOLIDADOS', conexión 162.CL_CALIDAD.
  UPDATE [CL_CALIDAD].[dbo].[TBL_ISN_ENVIOS_CONSOLIDADO]
  SET [FECHA DE CARGA] = CAST(GETDATE()AS date)
  WHERE [FECHA DE CARGA] IS NULL
